global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-service"
    static_configs:
      - targets: ["api:3001"]
    metrics_path: /metrics

  - job_name: "item-service"
    static_configs:
      - targets: ["item-service:3002"]
    metrics_path: /metrics

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15672"]
    metrics_path: /metrics

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
