global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-service"
    static_configs:
      - targets: ["api:80"]
    metrics_path: /metrics

  - job_name: "item-service"
    static_configs:
      - targets: ["item-service:80"]
    metrics_path: /metrics

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
    metrics_path: /metrics

  # - job_name: "mongodb" # Removed because it was too many pods for free bunnyshell
  #   static_configs:
  #     - targets: ["mongodb-exporter:9216"]
