name: Bunnyshell - Deploy Preview Environment
on:
  workflow_run:
    workflows:
      - "Bunnyshell - Prepare Preview Environment Configuration"
    types:
      - completed
permissions:
  pull-requests: write
jobs:
  load-artifact-from-reusable:
    name: Load artifact values
    uses: bunnyshell/workflows/.github/workflows/load-artifact.yaml@v2
    with:
      workflow_run_id: ${{ github.event.workflow_run.id }}

  prepare-config:
    name: Prepare Bunnyshell Config
    needs: load-artifact-from-reusable
    runs-on: ubuntu-latest
    outputs:
      modified-yaml: ${{ steps.modify-yaml.outputs.yaml }}
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.load-artifact-from-reusable.outputs.skip-deployment == 'false' }}
    steps:
      - name: Generate Random Password
        id: password
        run: |
          # Generate password without special characters
          RANDOM_PASSWORD=$(openssl rand -hex 16)
          echo "PASSWORD=$RANDOM_PASSWORD" >> $GITHUB_OUTPUT

      - name: Debug YAML
        env:
          ORIGINAL_YAML: ${{ needs.load-artifact-from-reusable.outputs.bunnyshell-yaml-contents }}
        run: |
          # Decode the base64 encoded YAML for debugging
          echo "$ORIGINAL_YAML" | base64 -d > original-bunnyshell.yaml
          cat original-bunnyshell.yaml

      - name: Modify Bunnyshell YAML
        id: modify-yaml
        env:
          ORIGINAL_YAML: ${{ needs.load-artifact-from-reusable.outputs.bunnyshell-yaml-contents }}
        run: |
          # First decode the base64 encoded YAML
          echo "$ORIGINAL_YAML" | base64 -d > temp-bunnyshell.yaml

          # Then replace the placeholder with the password
          cat temp-bunnyshell.yaml | sed "s|{{ env.MONGO_PASSWORD }}|${{ steps.password.outputs.PASSWORD }}|g" > modified-bunnyshell.yaml

          # Debug the modified YAML
          echo "Modified YAML:"
          cat modified-bunnyshell.yaml

          # Encode it back to base64
          MODIFIED_YAML=$(cat modified-bunnyshell.yaml | base64 -w 0)
          echo "yaml=$MODIFIED_YAML" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy Environment
    needs: [load-artifact-from-reusable, prepare-config]
    uses: bunnyshell/workflows/.github/workflows/deploy-env.yaml@v2
    concurrency: bns-deploy-${{ needs.load-artifact-from-reusable.outputs.pr-number }}
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.load-artifact-from-reusable.outputs.skip-deployment == 'false' }}
    with:
      pr-number: ${{ needs.load-artifact-from-reusable.outputs.pr-number }}
      project-id: "Z9rDV3bXAb"
      cluster-id: "LENQxkjMm6"
      env-name: "Demo PR #${{ needs.load-artifact-from-reusable.outputs.pr-number }}"
      bunnyshell-yaml-contents: ${{ needs.prepare-config.outputs.modified-yaml }}
      comment-on-pr: true
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
