name: DevOps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint-api:
    runs-on: ubuntu-latest
    name: Lint API
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/api/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/api
      - name: Run ESLint
        run: npx eslint . --ext .js
        working-directory: ./services/api

  lint-item-service:
    runs-on: ubuntu-latest
    name: Lint Item Service
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/item-service/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/item-service
      - name: Run ESLint
        run: npx eslint . --ext .js
        working-directory: ./services/item-service

  test-api:
    runs-on: ubuntu-latest
    name: Test API
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/api/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/api
      - name: Run tests
        run: npm test
        working-directory: ./services/api

  test-item-service:
    runs-on: ubuntu-latest
    name: Test Item Service
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/item-service/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/item-service
      - name: Run tests
        run: npm test
        working-directory: ./services/item-service

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint-api, lint-item-service, test-api, test-item-service]
    strategy:
      matrix:
        service: [api, item-service]
    name: Docker build ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: false
          load: true
          tags: ${{ matrix.service }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-readme-badges:
    runs-on: ubuntu-latest
    if: always()
    needs: [lint-api, lint-item-service, test-api, test-item-service]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Update README badges
        run: |
          REPO="${{ github.repository }}"

          # Replace the entire table with a correctly formatted one
          awk -v repo="$REPO" '
          BEGIN { in_table = 0 }

          /^## Service Status/ {
            print $0
            print ""
            print "| Service      | Tests                                                                                            | Lint                                                                                            |"
            print "| ------------ | ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------- |"
            print "| API Service  | [![API Tests](https://github.com/" repo "/actions/workflows/ci.yml/badge.svg?event=push&job=test-api)](https://github.com/" repo "/actions/workflows/ci.yml) | [![API Lint](https://github.com/" repo "/actions/workflows/ci.yml/badge.svg?event=push&job=lint-api)](https://github.com/" repo "/actions/workflows/ci.yml) |"
            print "| Item Service | [![Item Tests](https://github.com/" repo "/actions/workflows/ci.yml/badge.svg?event=push&job=test-item-service)](https://github.com/" repo "/actions/workflows/ci.yml) | [![Item Lint](https://github.com/" repo "/actions/workflows/ci.yml/badge.svg?event=push&job=lint-item-service)](https://github.com/" repo "/actions/workflows/ci.yml) |"
            in_table = 1
            next
          }

          /^## Architecture/ {
            in_table = 0
            print ""
            print $0
          }

          !in_table { print $0 }

          ' README.md > README.md.new

          mv README.md.new README.md

          cat README.md

      - name: Commit README changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README badges [skip ci]" || echo "No changes to commit"
          git push
