name: DevOps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint-api:
    runs-on: ubuntu-latest
    name: Lint API
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/api/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/api
      - name: Run ESLint
        run: npx eslint . --ext .js
        working-directory: ./services/api

  lint-item-service:
    runs-on: ubuntu-latest
    name: Lint Item Service
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/item-service/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/item-service
      - name: Run ESLint
        run: npx eslint . --ext .js
        working-directory: ./services/item-service

  test-api:
    runs-on: ubuntu-latest
    name: Test API
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/api/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/api
      - name: Run tests
        run: npm test
        working-directory: ./services/api

  test-item-service:
    runs-on: ubuntu-latest
    name: Test Item Service
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./services/item-service/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./services/item-service
      - name: Run tests
        run: npm test
        working-directory: ./services/item-service

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint-api, lint-item-service, test-api, test-item-service]
    strategy:
      matrix:
        service: [api, item-service]
    name: Docker build ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: false
          load: true
          tags: ${{ matrix.service }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-readme-badges:
    runs-on: ubuntu-latest
    if: always()
    needs: [lint-api, lint-item-service, test-api, test-item-service]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Get job statuses
        id: statuses
        run: |
          # Set statuses based on job needs context
          # These will return 'success', 'failure', etc.
          echo "api_lint_status=${{ needs.lint-api.result }}" >> $GITHUB_OUTPUT
          echo "item_lint_status=${{ needs.lint-item-service.result }}" >> $GITHUB_OUTPUT
          echo "api_test_status=${{ needs.test-api.result }}" >> $GITHUB_OUTPUT
          echo "item_test_status=${{ needs.test-item-service.result }}" >> $GITHUB_OUTPUT

      - name: Update README badges
        run: |
          REPO="${{ github.repository }}"

          # Set colors based on job statuses
          API_LINT_COLOR="${{ steps.statuses.outputs.api_lint_status == 'success' && 'success' || 'critical' }}"
          ITEM_LINT_COLOR="${{ steps.statuses.outputs.item_lint_status == 'success' && 'success' || 'critical' }}"
          API_TEST_COLOR="${{ steps.statuses.outputs.api_test_status == 'success' && 'success' || 'critical' }}"
          ITEM_TEST_COLOR="${{ steps.statuses.outputs.item_test_status == 'success' && 'success' || 'critical' }}"

          # Replace the entire table with badges using shields.io
          awk -v repo="$REPO" -v api_lint="$API_LINT_COLOR" -v item_lint="$ITEM_LINT_COLOR" -v api_test="$API_TEST_COLOR" -v item_test="$ITEM_TEST_COLOR" '
          BEGIN { in_table = 0 }

          /^## Service Status/ {
            print $0
            print ""
            print "| Service      | Tests                                                                                            | Lint                                                                                            |"
            print "| ------------ | ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------- |"
            print "| API Service  | [![API Tests](https://img.shields.io/badge/tests-" api_test "-brightgreen)](https://github.com/" repo "/actions/workflows/ci.yml) | [![API Lint](https://img.shields.io/badge/lint-" api_lint "-brightgreen)](https://github.com/" repo "/actions/workflows/ci.yml) |"
            print "| Item Service | [![Item Tests](https://img.shields.io/badge/tests-" item_test "-brightgreen)](https://github.com/" repo "/actions/workflows/ci.yml) | [![Item Lint](https://img.shields.io/badge/lint-" item_lint "-brightgreen)](https://github.com/" repo "/actions/workflows/ci.yml) |"
            in_table = 1
            next
          }

          /^## Architecture/ {
            in_table = 0
            print ""
            print $0
          }

          !in_table { print $0 }
          ' README.md > README.md.new

          mv README.md.new README.md
