name: Docker Build

on:
  push:
    branches: [main]
    paths:
      - "services/api/**"
      - "services/item-service/**"
      - ".github/workflows/docker-build.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/api/**"
      - "services/item-service/**"
      - ".github/workflows/docker-build.yml"
  workflow_run:
    workflows:
      - API Lint
      - API Tests
      - Item Service Lint
      - Item Service Tests
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        service: [api, item-service]
    name: Docker build ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: false
          load: true
          tags: ${{ matrix.service }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
